### ISSUE TITLE
Can't get created/rendered/destroyed callbacks to work properly

### ISSUE THREAD

**Issue by arboleya** [gadicc/meteor-famous-views#199] opened 2015-01-06 14:50 UTC
Hi everyone, I've just updated from `0.1.26` to `0.1.30` and all of my `Template.name.rendered` callbacks suddenly stop working.

So I build a sample app to investigate the problem, it follows this structure and uses IronRouter:

````handlebars
<template name='AppLayout'>
  {{#famousContext id="app-layout-context"}}

    {{#ContainerSurface translate='[40, 40, 0]'}}
      {{> yield }}
    {{/ContainerSurface}}

  {{/famousContext}}
</template>

<template name='AppIndex'>
   {{#ContainerSurface}}
     {{> _item}}
     {{> _item}}
     {{> _item}}
  {{/ContainerSurface}}
</template>

<template name='_item'>
  {{#Surface}}Item{{/Surface}}
</template>
````

````javascript
Template.AppIndex.created = function(){
  console.log('app:index - created');
}
Template.AppIndex.rendered = function(){
  console.log('app:index - rendered');
}
Template.AppIndex.destroyed = function(){
  console.log('app:index - destroyed');
}

Template._item.created = function(){
  console.log('_item - created');
}
Template._item.rendered = function(){
  console.log('_item - rendered');
}
Template._item.destroyed = function(){
  console.log('_item - destroyed');
}
````

This gives me the following output:

> Entering page

````
app:index - created
_item - created
_item - created
_item - created
````

> Exiting page (navigating to another route)

````
app:index - destroyed
````

# Problems

1. When entering page, just the `created` callback works. The `rendered` is never called.
1. When exiting page, the `destroyed` callback works for the top template, but not for the included templates.

Checking the  documentation I've seen this (which I'm guessing is new):

> When called via template inclusion, like {{>View template="x"}}, all the regular Meteor template stuff applies, so you can do things in Template.x.rendered = function() { }, setup events, etc.

So I went down and refactored my template inclusion to be as such:

````handlebars
<template name='AppIndex'>
   {{#ContainerSurface}}
     {{>Surface template='_item'}}
     {{>Surface template='_item'}}
     {{>Surface template='_item'}}
  {{/ContainerSurface}}
</template>

<template name='_item'>
  Item
</template>
````

And this gave me the following output:

> Entering page

````
app:index - created
_item - created
_item - created
_item - created
_item - rendered
_item - rendered
_item - rendered
````

> Exiting page (navigating to another route)

````
app:index destroyed
````

# Problems

1. When entering page, `rendered` callback works only for included templates, but not for the main one. (which gets rendered automatically by IronRouter)
1. When exiting page, `destroyed` callbacks doesn't work for any template

# Conclusion

What am I possibly doing wrong? :)

Thanks

**Comment by arboleya** [comment] 2015-01-06 15:10
I've created a sample repo demonstrating what I've just explained.

https://github.com/arboleya/famous-views-meteor-template-callbacks

Just clone it and start with the usual `meteor`, then open http://localhost and navigate between `Home` and `Section`.

Leave the console opened to see the log messages.

**Comment by jordangarside** [comment] 2015-01-23 00:49
Same +1

**Comment by gadicc** [comment] 2015-01-24 11:32
Hey, sorry, this is quite a serious issue... thanks for reporting!  Apologies for the long delay, I've been away travelling in the holidays with very limited internet, and am only slowly getting back into the swing of things now.

Can you see if `v0.1.31-pre.1` fixes your issue?  I did test against the repo you provided (thanks!).  I guess this is a common case but regrettably not the exact pattern I was testing against before I released the change.  For now I've tried to just revert to the old behavior.

Thanks for all the patience!  Hope you had holiday too :)

**Comment by jordangarside** [comment] 2015-01-25 21:34
Will try tomorrow, Thanks a lot @gadicc

**Comment by vplifer** [comment] 2015-01-26 15:00
I checked. Problem solved for me. Thank's a lot.

**Comment by jordangarside** [comment] 2015-01-27 03:27
So 0.1.31-pre.2 fixed rendered callbacks, but it broke SequentialLayout for me.

**Comment by gadicc** [comment] 2015-01-27 17:53
Oh dear, thanks for reporting back!

If your `SequentialLayout` relied on `famousEach`, there was a [bug](https://github.com/gadicc/meteor-famous-views/commit/bf30d56d7e64407426122104e5fb9e8d0478519e) in `v0.1.31-pre.2` (but not `-pre.1`) that was fixed in master, and that I've just released now in `v0.1.31-pre.3`; would you mind checking against that too?

Otherwise I'd love a reproduction that I can test against... what exactly is not working about it now?

Thanks for all your time on this.   And thanks, @vplifer, too for your report back.

**Comment by jordangarside** [comment] 2015-01-27 20:04
This is broken for me (tested in v0.1.31-pre.3 as well)
```
+ContainerSurface class='tabsContainer' size='[undefined, 44]' translate='[0,0,5]' origin='[0,1]' align='[0,1]'
	+SequentialLayout direction='1'
		+Surface class='tabItemContainer threeTabs' size='[true, 44]'
			div(class=tabClasses.one onclick='Session.set("currentTab", "1")')
				| tab1
		+Surface class='tabItemContainer threeTabs' size='[true, 44]'
			div(class=tabClasses.two onclick='Session.set("currentTab", "2")')
				| tab2
		+Surface class='tabItemContainer threeTabs' style='width:auto' size='[true, 44]'
			div(class=tabClasses.three onclick='Session.set("currentTab", "3")')
				| tab3
```

In v0.1.29 this will layout my tabs on the bottom of the screen from left to right.
In v0.1.31-pre.3 it will lay them out on the bottom of the screen on top of each other.

This is the CSS on the tabs
```
.tabsContainer
	background-color: white
	color: black
	font-weight: 900
	font-size: 16px
	.tabItemContainer
		&.threeTabs
			width: 33.3vw
		&.twoTabs
			width: 50vw
		.tabItem
			line-height: 44px
			text-align: center
			transition: background-color 0.6s
			&.active
				background-color: #01f8ff
```

**Comment by gadicc** [comment] 2015-01-27 20:31
Thanks!  Will take a proper look at this tomorrow.  Does `direction="X"` work?  We did some changes there, but I think we should accept both values.  If it's that it will be easy to fix.

**Comment by jordangarside** [comment] 2015-01-27 20:43
Turns out changing to `direction="X"` fixes it.

Thanks @gadicc

**Comment by Nauzer** [comment] 2015-01-27 20:49
+1 here.
0.1.29 no issues - rendered callback is running fine.

**Comment by gadicc** [comment] 2015-01-27 20:54
@jordangarside, ok brilliant... by 0.1.31, specifying `"1"` will work too, but at least now I know what broke.

@Nauzer, thanks for the report back!

Ok great, we are all on track for the next release, which should be out by the end of the week, as long as nothing else gets staged.  Thanks, everyone!

**Comment by gadicc** [comment] 2015-01-27 20:55
@Nauzer and sorry for the many hours :>  I usually handle regressions quite quickly but in this case it came up when I was away for the holidays.

**Comment by Nauzer** [comment] 2015-01-27 20:57
Glad it was resolved, no worries! 
Love your famo.us wrapper for Meteor, that saved many more hours of work ;-)

**Comment by gadicc** [comment] 2015-01-27 21:03
Thanks!  Show us what you're up to when you get a chance.

**Closed by gadicc** 2015-01-27 21:03 UTC
